version: '3.9'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: PostgresDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dotnet_network
  
  dotnet_rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: DamirkaSuperGod
      RABBITMQ_DEFAULT_PASS: Damirka
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    networks:
      - dotnet_network

  dotnet_minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: damir
      MINIO_ROOT_PASSWORD: damir
    networks:
      - dotnet_network

  dotnet_storage:
    image: dotnet-web-storage
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Storage.API/Dockerfile
    ports:
      - "8082:8082"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:8082
      MinioConfig__Username: damir
      MinioConfig__Password: damir
      MinioConfig__Endpoint: dotnet_minio
      MinioConfig__Port: 9000
      MinioConfig__WithSsl: false
    depends_on:
      - dotnet_minio
  
  dotnet_mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - dotnet_network

  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    networks:
      - dotnet_network
  
  dotnet_main:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
      - dotnet_minio
      - dotnet_mongodb
      - dotnet_jaeger
    environment:
      ASPNETCORE_URLS: "http://*:80"
      RabbitMqConfig__Username: "DamirkaSuperGod"
      RabbitMqConfig__Password: "Damirka"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
      ConnectionStrings__Default: Host=dotnet_postgres;Port=5432;Database=PostgresDb;Username=postgres;Password=root
    ports:
      - "9000:80"
    networks:
      - dotnet_network
  
  dotnet_mailing:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    environment:
      EmailConfig__Email: "cdbacjdorz@yandex.ru"
      EmailConfig__Host: "smtp.yandex.ru"
      EmailConfig__Port: "465"
      EmailConfig__Password: "vhcmwfdtshanwzak"
      RabbitMqConfig__Username: "DamirkaSuperGod"
      RabbitMqConfig__Password: "Damirka"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
    networks:
      - dotnet_network

volumes:
  postgres_data:
  mongodb_data:

networks:
  dotnet_network:
