version: '3.9'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: PostgresDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dotnet_network
    
  dotnet_rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: DamirkaSuperGod
      RABBITMQ_DEFAULT_PASS: Damirka
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dotnet_network

  dotnet_minio:
    image: minio/minio:latest

  dotnet_mongodb:
    image: mongo:latest

  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
    environment:
      ASPNETCORE_URLS: "http://*:80"
      RabbitMqConfig__Username: "DamirkaSuperGod"
      RabbitMqConfig__Password: "Damirka"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
      ConnectionStrings__Default: Host=dotnet_postgres;Port=5432;Database=PostgresDb;Username=postgres;Password=root
    ports:
      - "9000:80"
    networks:
      - dotnet_network
    
  dotnet_mailing:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    environment:
      EmailConfig__Email: "cdbacjdorz@yandex.ru"
      EmailConfig__Host: "smtp.yandex.ru"
      EmailConfig__Port: "465"
      EmailConfig__Password: "vhcmwfdtshanwzak"
      RabbitMqConfig__Username: "DamirkaSuperGod"
      RabbitMqConfig__Password: "Damirka"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
    networks:
      - dotnet_network
      
  dotnet_storage:
    image: dotnet-web

volumes:
  postgres_data:

networks:
  dotnet_network: